// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1683371563);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1683371256);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1683371236);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1683371376);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1683371498);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1683371286);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.addedImportButton", true);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{e1e3e743-8494-4557-a65a-1326fe625386}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1683371226);
user_pref("browser.laterrun.bookkeeping.sessionCount", 4);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{8bd45285-3185-4ed7-94d1-39299a831230}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230403141754");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage_override.buildID", "20230403141754");
user_pref("browser.startup.homepage_override.mstone", "102.10.0");
user_pref("browser.startup.lastColdStartupCheck", 1683371534);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"import-button\",\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"PersonalToolbar\",\"toolbar-menubar\",\"TabsToolbar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1683371231612");
user_pref("distribution.iniFile.exists.appversion", "102.10.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1683371563);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230403141754");
user_pref("extensions.lastAppVersion", "102.10.0");
user_pref("extensions.lastPlatformVersion", "102.10.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"cc7648ad-e67d-48f2-8266-84d430e40b8c\",\"formautofill@mozilla.org\":\"8e9ec7f7-7b5a-4338-887b-86376774f750\",\"pictureinpicture@mozilla.org\":\"5beb0b35-b4cd-42f5-9d25-7f7ecc81a6ad\",\"screenshots@mozilla.org\":\"795407bf-cb3f-4bca-bea4-c2749a15883c\",\"webcompat-reporter@mozilla.org\":\"a1824304-6138-4fe4-ab5d-aebcab9d8cca\",\"webcompat@mozilla.org\":\"2e33d67e-1e07-46b0-98a0-efd8595d02d8\",\"default-theme@mozilla.org\":\"ce6aaffb-ba50-434d-b540-8722c58d8e94\",\"addons-search-detection@mozilla.com\":\"34c84d63-2427-41d4-9304-1e2bb61cdf56\",\"google@search.mozilla.org\":\"34ec280b-ad77-4849-a65e-9c1dc6394df5\",\"amazondotcom@search.mozilla.org\":\"5a1061b9-c5a7-4032-94f5-a946bf32dc6c\",\"wikipedia@search.mozilla.org\":\"3dc6c8ab-8000-404f-b071-fd8a8aac29a6\",\"bing@search.mozilla.org\":\"c1795eae-0527-4e36-b1d6-ddc021658239\",\"ddg@search.mozilla.org\":\"a859bcd5-8180-410f-bb2f-8417eada69e6\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1683371233);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-manager.buildID", "20230403141754");
user_pref("media.gmp-manager.lastCheck", 1683371375);
user_pref("media.gmp-manager.lastEmptyCheck", 1683371375);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "c594c96c-519d-4464-88bb-6625c859b3e0");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1683371532);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230403141754");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
